name: MineTP
version: 1.0
description: MineTP enables you to teleport offline players.
author: Raith Thomas
webseite: http://www.xtrsource.com

main: com.xtrsource.minetp.MineTP

commands:
    mtp:
        description: 'Main command of MineTP'
        usage: 'Usage: /mtp (remove) <player>'